services:
  skautapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - ConnectionStrings__umbracoDbDSN=Data Source=/app/umbraco/Data/Modry_zivot.sqlite.db;Cache=Shared;
      - Umbraco__CMS__Runtime__Mode=Production
    volumes:
      - ./umbraco/Data:/app/umbraco/Data
    restart: always