version: '3.8'

services:
  skautapp:
    build: .
    container_name: skautapp_web
    restart: always
    ports:
      - "80:8080"
    volumes:
      # Propojení databáze a médií s diskem serveru
      - ./umbraco/Data:/app/umbraco/Data
      - ./umbraco_media:/app/wwwroot/media